# Generated by Django 5.1.2 on 2025-03-23 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0047_alter_game_date_played'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['handicap', 'last_name', 'first_name'], 'verbose_name_plural': 'players'},
        ),
        migrations.AddField(
            model_name='game',
            name='use_groups',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='first_name',
            field=models.CharField(default='Not Defined', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='last_name',
            field=models.CharField(default='Not Defined', max_length=32),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Eagle', 'Eagle'), ('Birdie', 'Birdie'), ('Par', 'Par')], default='Par', max_length=32)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.game')),
                ('players', models.ManyToManyField(through='dashboard.PlayerMembership', to='dashboard.player')),
            ],
            options={
                'verbose_name_plural': 'groups',
                'ordering': ['game', 'name'],
            },
        ),
        migrations.AddField(
            model_name='playermembership',
            name='group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='dashboard.group'),
        ),
    ]
