# Generated by Django 5.1.2 on 2025-03-30 12:39

import djmoney.models.fields
import djmoney.models.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0048_alter_player_options_game_use_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='single_cost',
            field=djmoney.models.fields.MoneyField(decimal_places=0, default=Decimal('5'), default_currency='USD', max_digits=3, validators=[djmoney.models.validators.MinMoneyValidator({'USD': 5}), djmoney.models.validators.MaxMoneyValidator({'USD': 100})], verbose_name='Per-Player singles buy-in'),
        ),
        migrations.AddField(
            model_name='game',
            name='single_cost_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'USD $')], default='USD', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='game',
            name='use_singles',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='buy_in',
            field=djmoney.models.fields.MoneyField(decimal_places=0, default=Decimal('10'), default_currency='USD', max_digits=3, validators=[djmoney.models.validators.MinMoneyValidator({'USD': 10}), djmoney.models.validators.MaxMoneyValidator({'USD': 100})], verbose_name='Per-player random draw buy-in'),
        ),
        migrations.AlterField(
            model_name='game',
            name='skin_cost',
            field=djmoney.models.fields.MoneyField(decimal_places=0, default=Decimal('1'), default_currency='USD', max_digits=3, validators=[djmoney.models.validators.MinMoneyValidator({'USD': 1}), djmoney.models.validators.MaxMoneyValidator({'USD': 100})], verbose_name='Per-hole skin buy-in'),
        ),
    ]
