# Generated by Django 5.1.2 on 2025-03-30 13:30

import djmoney.models.fields
import djmoney.models.validators
from decimal import Decimal
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0049_game_single_cost_game_single_cost_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='use_singles',
        ),
        migrations.RemoveField(
            model_name='game',
            name='use_skins',
        ),
        migrations.AlterField(
            model_name='game',
            name='buy_in',
            field=djmoney.models.fields.MoneyField(decimal_places=0, default=Decimal('10'), default_currency='USD', max_digits=3, validators=[djmoney.models.validators.MinMoneyValidator({'USD': 0}), djmoney.models.validators.MaxMoneyValidator({'USD': 100})], verbose_name='Per-player random draw buy-in'),
        ),
        migrations.AlterField(
            model_name='game',
            name='single_cost',
            field=djmoney.models.fields.MoneyField(decimal_places=0, default=Decimal('5'), default_currency='USD', max_digits=3, validators=[djmoney.models.validators.MinMoneyValidator({'USD': 0}), djmoney.models.validators.MaxMoneyValidator({'USD': 100})], verbose_name='Per-Player singles buy-in'),
        ),
        migrations.AlterField(
            model_name='game',
            name='skin_cost',
            field=djmoney.models.fields.MoneyField(decimal_places=0, default=Decimal('1'), default_currency='USD', max_digits=3, validators=[djmoney.models.validators.MinMoneyValidator({'USD': 0}), djmoney.models.validators.MaxMoneyValidator({'USD': 100})], verbose_name='Per-hole skin buy-in'),
        ),
    ]
