# Generated by Django 5.1.2 on 2025-03-30 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0050_remove_game_use_singles_remove_game_use_skins_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playermembership',
            name='singles',
            field=models.BooleanField(default=False),
        ),
    ]
