# Generated by Django 5.1.2 on 2025-04-04 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0051_playermembership_singles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playermembership',
            name='game',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.game'),
        ),
    ]
