# Generated by Django 5.1.2 on 2025-04-07 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0052_alter_playermembership_game'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playermembership',
            unique_together=set(),
        ),
        migrations.AlterOrderWithRespectTo(
            name='playermembership',
            order_with_respect_to='player',
        ),
    ]
