# Generated by Django 5.1.2 on 2025-04-08 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0053_alter_playermembership_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='game',
            unique_together={('course', 'date_played')},
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('name', 'game')},
        ),
        migrations.AlterUniqueTogether(
            name='holescore',
            unique_together={('player', 'hole')},
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('name', 'game')},
        ),
    ]
