# Generated by Django 5.1.2 on 2025-04-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0054_alter_game_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='golfcourse',
            name='par',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='golfcourse',
            name='points',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
    ]
