# Generated by Django 5.1.2 on 2025-04-19 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0055_golfcourse_par_golfcourse_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.game')),
                ('players', models.ManyToManyField(through='dashboard.PlayerMembership', to='dashboard.player')),
            ],
            options={
                'verbose_name_plural': 'randomteams',
                'ordering': ['game', 'name'],
                'unique_together': {('name', 'game')},
            },
        ),
        migrations.AddField(
            model_name='playermembership',
            name='random',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='dashboard.randomteam'),
        ),
    ]
