# Generated by Django 5.1.2 on 2025-04-21 14:08

import djmoney.models.fields
import djmoney.models.validators
from decimal import Decimal
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0056_randomteam_playermembership_random'),
    ]

    operations = [
        migrations.AddField(
            model_name='playermembership',
            name='random_money',
            field=djmoney.models.fields.MoneyField(decimal_places=0, default=Decimal('0'), default_currency='USD', max_digits=3, validators=[djmoney.models.validators.MinMoneyValidator({'USD': 0}), djmoney.models.validators.MaxMoneyValidator({'USD': 1000})], verbose_name='Random draw money won'),
        ),
        migrations.AddField(
            model_name='playermembership',
            name='random_money_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'USD $')], default='USD', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='playermembership',
            name='single_money',
            field=djmoney.models.fields.MoneyField(decimal_places=0, default=Decimal('0'), default_currency='USD', max_digits=3, validators=[djmoney.models.validators.MinMoneyValidator({'USD': 0}), djmoney.models.validators.MaxMoneyValidator({'USD': 1000})], verbose_name='Singles money won'),
        ),
        migrations.AddField(
            model_name='playermembership',
            name='single_money_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'USD $')], default='USD', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='playermembership',
            name='skin_money',
            field=djmoney.models.fields.MoneyField(decimal_places=0, default=Decimal('0'), default_currency='USD', max_digits=3, validators=[djmoney.models.validators.MinMoneyValidator({'USD': 0}), djmoney.models.validators.MaxMoneyValidator({'USD': 1000})], verbose_name='Skins money won'),
        ),
        migrations.AddField(
            model_name='playermembership',
            name='skin_money_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'USD $')], default='USD', editable=False, max_length=3),
        ),
    ]
