# Generated by Django 5.1.2 on 2025-04-24 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0057_playermembership_random_money_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playermembership',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.game'),
            preserve_default=False,
        ),
    ]
