# Generated by Django 5.1.2 on 2025-05-06 13:34

import dashboard.models
import django.db.models.deletion
import djmoney.models.fields
import djmoney.models.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0058_alter_playermembership_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='golfcourse',
            name='hole_count',
        ),
        migrations.RemoveField(
            model_name='golfcourse',
            name='par',
        ),
        migrations.RemoveField(
            model_name='golfcourse',
            name='points',
        ),
        migrations.RemoveField(
            model_name='team',
            name='handicap',
        ),
        migrations.CreateModel(
            name='LeagueScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handicap_played', models.SmallIntegerField(blank=True, default=None, null=True)),
                ('handicap_adjustment', models.SmallIntegerField(blank=True, default=None, null=True)),
                ('score', models.SmallIntegerField(blank=True, default=None, null=True)),
                ('points', models.SmallIntegerField(blank=True, default=None, null=True)),
                ('random_won_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'USD $')], default='USD', editable=False, max_length=3)),
                ('random_won', djmoney.models.fields.MoneyField(decimal_places=0, default=Decimal('0'), default_currency='USD', max_digits=3, validators=[djmoney.models.validators.MinMoneyValidator({'USD': 0}), djmoney.models.validators.MaxMoneyValidator({'USD': 1000})], verbose_name='Random draw money won')),
                ('skins_won_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'USD $')], default='USD', editable=False, max_length=3)),
                ('skins_won', djmoney.models.fields.MoneyField(decimal_places=0, default=Decimal('0'), default_currency='USD', max_digits=3, validators=[djmoney.models.validators.MinMoneyValidator({'USD': 0}), djmoney.models.validators.MaxMoneyValidator({'USD': 1000})], verbose_name='Skins money won')),
                ('singles_won_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'USD $')], default='USD', editable=False, max_length=3)),
                ('singles_won', djmoney.models.fields.MoneyField(decimal_places=0, default=Decimal('0'), default_currency='USD', max_digits=3, validators=[djmoney.models.validators.MinMoneyValidator({'USD': 0}), djmoney.models.validators.MaxMoneyValidator({'USD': 1000})], verbose_name='Singles money won')),
                ('course', models.ForeignKey(default=dashboard.models.get_ttcc_course, on_delete=django.db.models.deletion.PROTECT, to='dashboard.golfcourse')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.player')),
            ],
        ),
    ]
