databases:
  - name: luckofthedraw-golfclub-db
    plan: free
    region: ohio
    databaseName: rsgolfdb
    user: rsgolfdb_user

services:
  - type: web
    plan: free
    region: ohio
    name: luckofthedraw-golfclub
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn core.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: luckofthedraw-golfclub-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4

